REQUIRED_PROPERTIES = ["volume", "density", "structuralAsset"]

# Keys
APPLICATION_ID = "applicationId"
ARC = "Objects.Geometry.Arc"
CIRCLE = "Objects.Geometry.Circle"
DENSITY = "density"
ELEMENTS = "elements"
ID = "id"
LINE = "Objects.Geometry.Line"
MASS = "mass"
MATERIAL_QUANTITIES = "Material Quantities"
NAME = "name"
PROPERTIES = "properties"
SOURCE_APPLICATION = "sourceApplication"
SPECKLE_TYPE = "speckle_type"
STRUCTURAL_ASSET = "structuralAsset"
UNITS = "units"
VALUE = "value"
VOLUME = "volume"
